version: "3"
services:
  jekyll:
    image: ruby:2.4.1
    command: bundle exec jekyll serve --force_polling --host 0.0.0.0 --incremental
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
      - bundle:/usr/local/bundle
    working_dir: /app
volumes:
  bundle:
    driver: local
